algoritmo "Temperaturas"
// Função : Converter Celsius para Fahrenheint
// Autor : João Pedro
// Data : 09/03/2023
// Seção de Declarações 
var

F,C:real

inicio
// Entrada
escreval ("------------------------")
escreval ("Insira quantos graus celsius deseja converter para Fahrenheint: ")
leia(C)

escreval ("------------------------")
//Processamento
F <- (9*C+160)/5
//saida
escreval ("A conversão de ",C,"°C é igual a ",F,"°F")
fimalgoritmo
