algoritmo "idade"
// Função : Verificar se tu é maior de idade
// Autor :  João Pedro
// Data : 18/05/2023
// Seção de Declarações 
var

idade:real
nome:caractere

inicio
//entrada
escreval("Insira seu nome")
leia(nome)
escreval("------------------")
escreval("Insira sua idade")
leia(idade)
escreval("------------------")
//processamento
se idade > 18 entao
   escreval(nome," é maior de idade")
senao
   escreval(nome," é menor de idade")
fimse

fimalgoritmo
