algoritmo "exercicio1"
// Função : ver se um número é maior que 10
// Autor :  João Pedro
// Data : 18/05/2023
// Seção de Declarações 
var

numero:real

inicio
//entrada
escreval("Insira um número")
leia(numero)
escreval("------------------")
//processamento
se numero > 10 entao
   escreval("seu número é maior que 10")
senao
   escreval("Seu número é menor que 10")
fimse

fimalgoritmo
