algoritmo "Entre 100 e 200"
// Função : Verificar se um número está no intervalo de 100 e 200
// Autor : João Pedro Morangoni
// Data : 25/05/2023
// Seção de Declarações 
var
num:real

inicio
escreval("Insira um número: ")
leia(num)
escreval("------------------")
se (num>100) e (num<200) entao
   escreval("Seu número está no intervalo entre 100 e 200")
senao
   escreval("Seu número não está no intervalo de 100 e 200")
fimse
fimalgoritmo
